language: c
script:
- make all
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - rc
    - gcc-4.8
notifications:
  slack:
    secure: jyOsEs7e7HPmT+4zo6wtLQc0XIopWfZjUaTTlgcnR5M/QA+SrhU5izXjroKH03D8hXWXrCSss2P4JobfPnReshn9GQh7RNIYzDRUTygx/SYRY8/QotP5oQwIPP3W/8OcEg7coFsHGh1EIhEU9mwOqLUYSFcnEmvK9pcCNoIg9Ys+4LuYz05EsqkLm/IkriYC9gN2zTbsBOQiABSUPa5utFwLKRtqMzWIfIB6D7U1H7HRBEZ1d2McQQdsdhEe5XbSgdtZ44BwWO0EgaQX2vfL7PXWIy0xzlba+PFt3AvCJeN+v6Dtd2l8LnGN39gxbk5Cyl3X8uLmfva9wkVbDSl4H7qykcFbasem5bc8M619RKEueUhKKanVSHKYRmd8qvpSeOETUm00P2Wu1YWZuxdZuNR4HIMR3SYetS+dkkWHO75rx/yYhjf4pKjyoZ7F3ui8AGQ5KQG5G4QRtEYLS4AFNCMrkrv4dON3Gy/h+0U4vIILaZZ1zM/EFvIOPvr/pQaQJeY7M4eePGlr6K9GVVxCT9a2sqd4jfYikgoQvDRMeG1LNESl2T4AKB3Q14GKJvLscScn08ORBwRtNS+iDTI2KpAvw2Tqk8Iqu3lsUmLzDScJx4yhDwnDSjyOCq/8S7qliuIxzPxtW05Gc07Qw5+6jXjTepHBA0xHgJPN8u6l/VU=
